/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game.gui;

/**
 *
 * @author mathe
 */
public class GameGUI extends javax.swing.JFrame {

    /**
     * Creates new form GameGUI
     */
    public GameGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        a0 = new javax.swing.JButton();
        a1 = new javax.swing.JButton();
        a2 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        c0 = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new java.awt.GridLayout(3, 3));

        a0.setBackground(new java.awt.Color(255, 255, 255));
        a0.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        a0.setForeground(new java.awt.Color(0, 0, 0));
        a0.setBorder(null);
        a0.setLabel("");
        a0.setName("0"); // NOI18N
        a0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a0MouseClicked(evt);
            }
        });
        a0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a0ActionPerformed(evt);
            }
        });
        getContentPane().add(a0);
        a0.getAccessibleContext().setAccessibleName("a0");

        a1.setBackground(new java.awt.Color(255, 255, 255));
        a1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        a1.setForeground(new java.awt.Color(0, 0, 0));
        a1.setBorder(null);
        a1.setLabel("");
        a1.setName("1"); // NOI18N
        a1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1MouseClicked(evt);
            }
        });
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        getContentPane().add(a1);
        a1.getAccessibleContext().setAccessibleName("b0");

        a2.setBackground(new java.awt.Color(255, 255, 255));
        a2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        a2.setForeground(new java.awt.Color(0, 0, 0));
        a2.setBorder(null);
        a2.setLabel("");
        a2.setName("2"); // NOI18N
        a2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a2MouseClicked(evt);
            }
        });
        getContentPane().add(a2);
        a2.getAccessibleContext().setAccessibleName("c0");

        b0.setBackground(new java.awt.Color(255, 255, 255));
        b0.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        b0.setForeground(new java.awt.Color(0, 0, 0));
        b0.setBorder(null);
        b0.setLabel("");
        b0.setName("3"); // NOI18N
        b0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b0MouseClicked(evt);
            }
        });
        getContentPane().add(b0);
        b0.getAccessibleContext().setAccessibleName("a1");

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 0, 0));
        b1.setBorder(null);
        b1.setLabel("");
        b1.setName("4"); // NOI18N
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });
        getContentPane().add(b1);
        b1.getAccessibleContext().setAccessibleName("b1");

        b2.setBackground(new java.awt.Color(255, 255, 255));
        b2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 0, 0));
        b2.setBorder(null);
        b2.setLabel("");
        b2.setName("5"); // NOI18N
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
        });
        getContentPane().add(b2);
        b2.getAccessibleContext().setAccessibleName("c1");

        c0.setBackground(new java.awt.Color(255, 255, 255));
        c0.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        c0.setForeground(new java.awt.Color(0, 0, 0));
        c0.setBorder(null);
        c0.setLabel("");
        c0.setName("6"); // NOI18N
        c0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c0MouseClicked(evt);
            }
        });
        getContentPane().add(c0);
        c0.getAccessibleContext().setAccessibleName("a2");

        c1.setBackground(new java.awt.Color(255, 255, 255));
        c1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        c1.setForeground(new java.awt.Color(0, 0, 0));
        c1.setBorder(null);
        c1.setLabel("");
        c1.setName("7"); // NOI18N
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1MouseClicked(evt);
            }
        });
        getContentPane().add(c1);
        c1.getAccessibleContext().setAccessibleName("b2");

        c2.setBackground(new java.awt.Color(255, 255, 255));
        c2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        c2.setForeground(new java.awt.Color(0, 0, 0));
        c2.setBorder(null);
        c2.setLabel("");
        c2.setName("8"); // NOI18N
        c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c2MouseClicked(evt);
            }
        });
        getContentPane().add(c2);
        c2.getAccessibleContext().setAccessibleName("c2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    VirtualBoard board = new VirtualBoard();

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void a0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a0MouseClicked
        // TODO add your handling code here:
        board.change(a0);
        if(board.winnerREDUNDANT()){
        clearBitch();
        }
    }//GEN-LAST:event_a0MouseClicked

    private void a0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a0ActionPerformed

    private void a1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseClicked
        board.change(a1);
                if(board.winnerREDUNDANT()){
        clearBitch();
        }
    }//GEN-LAST:event_a1MouseClicked

    private void a2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2MouseClicked
        board.change(a2);// TODO add your handling code here:
                if(board.winnerREDUNDANT()){
        clearBitch();
        }
    }//GEN-LAST:event_a2MouseClicked

    private void b0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b0MouseClicked
        board.change(b0);
                if(board.winnerREDUNDANT()){
        clearBitch();
        }
    }//GEN-LAST:event_b0MouseClicked

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
        board.change(b1);
                if(board.winnerREDUNDANT()){
        clearBitch();
        }
    }//GEN-LAST:event_b1MouseClicked

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
        board.change(b2);
                if(board.winnerREDUNDANT()){
        clearBitch();
        }
    }//GEN-LAST:event_b2MouseClicked

    private void c0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c0MouseClicked
        board.change(c0);
                if(board.winnerREDUNDANT()){
        clearBitch();
        }
    }//GEN-LAST:event_c0MouseClicked

    private void c1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseClicked
        board.change(c1);
                if(board.winnerREDUNDANT()){
        clearBitch();
        }
    }//GEN-LAST:event_c1MouseClicked

    private void c2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MouseClicked
        board.change(c2);
                if(board.winnerREDUNDANT()){
        clearBitch();
        }
    }//GEN-LAST:event_c2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameGUI().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a0;
    private javax.swing.JButton a1;
    private javax.swing.JButton a2;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton c0;
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    // End of variables declaration//GEN-END:variables

    private void clearBitch() {
        a0.setText("");
        a1.setText("");
        a2.setText("");
        b0.setText("");
        b1.setText("");
        b2.setText("");
        c0.setText("");
        c1.setText("");
        c2.setText("");
        board.resetWinner();
    }
}
